import type { Metadata } from "next";
import "./globals.css";
import Navigation from "./components/Navigation";
import { Suspense } from "react";
import Loading from "./components/loading";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {" "}    <Navigation></Navigation>
    
        <Suspense fallback={<Loading />}> {children}</Suspense>
      </body>
    </html>
  );
}
